### ISSUE TITLE
Crawler does not work

### ISSUE THREAD

**Issue by wtfmejt** [hedii/php-crawler#29] opened 2017-07-22 10:19 UTC
I have added several of my websites to be crawled but the crawler does not seem able to start. Iam running PHP 7.0.21.

**Comment by hedii** [comment] 2017-07-22 10:21
Hi, I cannot help without any informations, debug, etc...

**Comment by wtfmejt** [comment] 2017-07-22 10:25
Hey hedii, thats my problem too. I do not see anything I could debug either. The image keeps spinning but I don't see any activity. If you could point me towards a direction I could start searching where it might go wrong.

**Comment by hedii** [comment] 2017-07-22 10:27
For many users, the main issue is their web server configuration (check closed issues).
Your site url must be something like example.com and not example.com/php-crawler or even worse example.com/php-crawler/public

**Comment by wtfmejt** [comment] 2017-07-22 10:31
I have set it up on a subdomain crawler.mydomain.com do you think that is the issue? I will have a look at those closed issues.

**Comment by hedii** [comment] 2017-07-22 10:35
check chrome devtools and find js error, network requests errors

**Comment by wtfmejt** [comment] 2017-07-22 10:38
I just did no JS or Network requests errors. Also nothing in the logfile or apache logs.

**Comment by bizmate** [comment] 2017-07-22 10:42
You have a personal setup problem. Get an application working and write logs on your apache/nginx or whatever you use first. You need to have access, error logs working and enable E_ALL error level ... also set it to display your php errors. Share screenshots instead of writing just 'it doesnt work'. If apache doesnt write logs it is not a php software problem but an apache misconfig

**Comment by wtfmejt** [comment] 2017-07-22 10:46
My other laravel apps have no problem reporting back all kinds of errors. Apache works perfectly aswell. I did not setup this inside WAMP or anything but on a server that hosts all kinds of websites. I tried figuring out why it does not do anything. Access and Error logs are clear. Iam currently downloading the whole setup to my local pc to dig into it and see where it might go wrong. Regarding your complaing about screenshots I could show you blank screenshots, I doubt those could help you understand my prob. I find it weird too that I do not see anything.

**Comment by hedii** [comment] 2017-07-22 10:47
@wtfmejt share a public url if you have it setup on a server

**Comment by bizmate** [comment] 2017-07-22 10:52
@wtfmejt you could show screenshots/logs/repo anything to be able to asses the problem just like @hedii asked. Also you mentioned the word 'image' are you using docker or a VM? push all the code on github (even if you replace some of the config)

**Comment by wtfmejt** [comment] 2017-07-22 10:53
@hedii I send you an email via your contact form on your website.

**Comment by hedii** [comment] 2017-07-22 10:57
it may not be the only issue, but your server respond with 502 on some requests:
![capture d ecran 2017-07-22 a 12 55 13](https://user-images.githubusercontent.com/5358048/28490563-589caa12-6edd-11e7-9771-7f73e8c85015.png)

**Comment by wtfmejt** [comment] 2017-07-22 10:58
@bizmate it is not running inside a VM sorry If you missunderstood me. The only thing I changed was the SQL credentials.

**Comment by wtfmejt** [comment] 2017-07-22 10:58
@hedii I restarted nginx and httpd maybe you got that error while it was restarting

**Comment by wtfmejt** [comment] 2017-07-22 11:04
@hedii there is also a info.php with phpinfo on that subdomain you can have a look there too

**Comment by hedii** [comment] 2017-07-22 11:10
@wtfmejt I have not used the crawler for a long time.
So i just cloned the repo on my mac, i followed the instructions from the readme, everything is running smoothly.

Your problem is a configuration problem, which cannot be resolved without debugging logs (laravel logs AND your webserver logs AND php logs AND why not syslog) that you cannot provide.

I am sorry but i cannot help you with that.

![capture d ecran 2017-07-22 a 13 06 30](https://user-images.githubusercontent.com/5358048/28490629-15290e04-6edf-11e7-92c9-ad58abda72dd.png)

**Comment by wtfmejt** [comment] 2017-07-22 11:13
Allright. Sorry for wasting your time. I told you all those logs look clean to me. I am waiting now for it to download to my PC and I will have a look at it. Furthermore I will do what you did and set it up on my mac aswell to check it out there. You can close this issue. I will send you an update via your website when I discover what is wrong so maybe others will not have to go through the same issue :). Thanks again!

**Comment by hedii** [comment] 2017-07-22 11:15
@wtfmejt you're welcome. Please share your updates here, so the other users can read it.
I'll reopen the issue when needed.

**Comment by wtfmejt** [comment] 2017-07-24 11:38
I had some time today and started tinkering abit to see how it works and I figured out that for some reason the command

exec('cd ' . base_path() . ' && php artisan crawler:crawl ' . $search->id . ' > /dev/null &');

Does not work there. If I run the command via the console it starts working and updating the webpage with all relevant information.

I have verified that the exec command works though through a separate php script that exec whoami.

**Comment by hedii** [comment] 2017-07-24 11:53
What is your operating system ?
What is the result of base_path() function ?
What is your web server user ?

**Comment by wtfmejt** [comment] 2017-07-24 12:01
- Centos 6.9
- I changed the base() path to the full path where the artisan file resides and it still did not work
- Classic cPanel setup nobody 

I placed a test.php file with a exec command in the public folder to see if it gets executed and it ran without issues. Also changed the cmd to Artisan::call to see if it would run but it did not work.

I was going to look into the app.js file but its minified to see if I can disable the ajax part at that point. I tried dd($search->id); before the exec to see if the id is passed correctly but I did not see any output because of the ajax probably.

**Comment by hedii** [comment] 2017-07-24 12:12
>  I figured out that for some reason the command

How did you figured it out? The command is supposed to return nothing.

In a console, please run this when your are on the crawler directory:
````
php artisan tinker

exec('cd ' . base_path() . ' && php artisan list');

exec('cd ' . base_path() . ' && php artisan list  > /dev/null &');
````

What is the output?

Also, i don't use centos even less with cpanel, but is /dev/null usable on your install?

Does the crawler work on your mac?

**Comment by wtfmejt** [comment] 2017-07-24 12:24
I ran the artisan directly inside the crawler folder and saw in my browser that it had started working getting urls and parsing them for emails. 

php artisan  crawler:crawl 1

user@domain.com [~/crawler]# php artisan tinker
Psy Shell v0.7.2 (PHP 7.0.21 — cli) by Justin Hileman
>>> exec('cd ' . base_path() . ' && php artisan list');
=> "  view:clear          Clear all compiled view files"
>>> exec('cd ' . base_path() . ' && php artisan list  > /dev/null &');
=> ""
>>>

Also /dev/null is usable in my install.

I had no time to test it yet on my mac I will do so in abit.

**Comment by hedii** [comment] 2017-07-24 13:20
well, i really don't know what is the problem with your install...

Try dumping some variable on the api controllers (SearchController) or on the command class, and see in chrome dev tools the api response. Or log the variables to the log file with laravel log capabilities (https://laravel.com/docs/5.4/errors#logging)

Maybe someone on centos / cpanel may try to reproduce this issue?

**Comment by spopicdev** [comment] 2017-07-24 14:02
C:\Users\stefa\php-crawler>php artisan tinker
Psy Shell v0.7.2 (PHP 5.6.25 ΓÇö cli) by Justin Hileman
>>> exec('cd ' . base_path() . ' && php artisan list');
=> "  view:clear          Clear all compiled view files"
>>> exec('cd ' . base_path() . ' && php artisan list  > /dev/null &');
The system cannot find the path specified.
=> ""

This is the output in my case, also, crawler is not working. When I start collecting emails, nothing happens.

Any solution for this?

**Comment by wtfmejt** [comment] 2017-07-24 14:29
@spiopicdev try

php artisan crawler:crawl 1

1 should be the id in the database of your first entered search

**Comment by spopicdev** [comment] 2017-07-24 14:40
@wtfmejt Nothing happens

**Comment by wtfmejt** [comment] 2017-07-24 14:55
@spopicdev did you verify you got the correct id from your searches table?

**Comment by spopicdev** [comment] 2017-07-25 11:34
@wtfmejt yup, I used another ID, because I manually deleted some IDs from DB

**Comment by spopicdev** [comment] 2017-07-25 14:59
My problem was with composer, it failed with installing some elements. Now it's working. Sorry for bothering, and thank you for your help and time.

**Comment by spopicdev** [comment] 2017-07-27 16:46
How can I export results emails from command line because I want to run this program on droplet?

**Comment by hedii** [comment] 2017-07-27 18:49
@spopicdev You have to write a command yourself, because file creation and file download are handled on a controller (https://github.com/hedii/php-crawler/blob/master/app/Http/Controllers/ResourceController.php#L25)

And **please open your own issue!** Your question is unrelated to this one.

**Comment by hedii** [comment] 2017-08-20 07:31
Closing due to no activity

**Closed as completed by hedii** 2017-08-20 07:31 UTC
