### ISSUE TITLE
Empty list of emails

### ISSUE THREAD

**Issue by sn4f** [hedii/php-crawler#31] opened 2017-11-25 14:35 UTC
Hi!
I have problem with crawling. When I put url and start crawler I always get 0 emails and 0 urls. Dont see any errors on laravel logs.

**Comment by sn4f** [comment] 2017-11-26 12:03
Ok this problem is only on https pages

**Comment by hedii** [comment] 2017-11-26 12:05
What is the exact url ?

**Comment by sn4f** [comment] 2017-11-26 12:06
for example https://katalog-firmy.net/

**Comment by hedii** [comment] 2017-11-26 12:27
@sn4f I just clean-installed the repo on my mac. I followed the instructions on the readme.

I started a new crawl for the url https://katalog-firmy.net/

Everything is ok as shown in the screenshot.

I am a mac user, i don't have access to a windows or linux machine right now. I don't know on which type of OS you are running this repo. Please find the issue on your OS, and if it is not a configuration issue (i really think your issue is a conf issue), please submit a pull request that will not break the crawler on other operating systems.

I am closing the issue for now, because I cannot reproduce any problem on my side.

<img width="1180" alt="capture d ecran 2017-11-26 a 13 20 18" src="https://user-images.githubusercontent.com/5358048/33239908-bf3a8176-d2ac-11e7-8e07-ec99e8872ff8.png">

**Closed as completed by hedii** 2017-11-26 12:27 UTC

**Comment by sn4f** [comment] 2017-11-26 12:28
I flush database and start crawler again - now its ok. Thanks for check

**Comment by sn4f** [comment] 2017-11-26 12:32
I use mariaDB mby this is a problem? again get this same problem :<

**Comment by hedii** [comment] 2017-11-26 12:34
I am also using mariadb

**Comment by sn4f** [comment] 2017-11-26 12:46
Hmm... when I use php artisan crawler:crawl command on command line then work.. mby I need to set cron?

**Comment by hedii** [comment] 2017-11-27 22:35
No need to setup a cron task. What is your operating system?
